ALTER TABLE radiographer_workload
ADD COLUMN IF NOT EXISTS mr_large_male_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS mr_large_female_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS mr_medium_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS mr_small_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_a_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_breast_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_heart_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_thy_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_cca_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_neck_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_pelvis_female_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS us_pelvis_male_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS dx_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS mg_teaching int4 DEFAULT 0,
ADD COLUMN IF NOT EXISTS cta_teaching int4 DEFAULT 0;
