const fs = require('fs');
let code = fs.readFileSync('services/store.ts', 'utf8');

const regexTo = /private mapToDbFields\(obj: any\) \{[\s\S]*?delete obj\[key\];\s*\}\s*\n\s*\}\);\s*\n\s*\}/;
const regexFrom = /private mapFromDbFields\(obj: any\) \{[\s\S]*?delete obj\[key\];\s*\}\s*\n\s*\}\);\s*\n\s*\}/;

const toDbFields = `private mapToDbFields(obj: any) {
    const mapping: Record<string, string> = {
      isRadiographer: "is_radiographer",
      isPartTime: "is_part_time",
      isHealthMgmt: "is_health_mgmt",
      healthMgmtLocation: "health_mgmt_location",
      isActive: "is_active",
      resignationDate: "resignation_date",
      groupIndex: "group_index",
      groupId: "group_id",
      mustChangePassword: "must_change_password",
      avatarUrl: "avatar_url",
      personalCycles: "personal_cycles",
      primaryStation: "primary_station",
      learningCapabilities: "learning_capabilities",
      excludedCapabilities: "excluded_capabilities",
      specialRoles: "special_roles",
      userId: "user_id",
      targetUserId: "target_user_id",
      returnDate: "return_date",
      approverId: "approver_id",
      processedAt: "processed_at",
      roleToSwap: "role_to_swap",
      targetApproval: "target_approval",
      permissions: "permissions",
      workTime: "work_time",
      displayOrder: "display_order",
      monthlyTargetShifts: "monthly_target_shifts",
      excludedDays: "excluded_days",
      excludedAutoScheduleLocations: "excluded_auto_schedule_locations",
      fixedShifts: "fixed_shifts",
      weekdaySettings: "weekday_settings",
      explanationTaskType: "explanation_task_type",
      isAutoGenerated: "is_auto_generated",
      doctorId: "doctor_id",
      startDate: "start_date",
      endDate: "end_date",
      startTime: "start_time",
      endTime: "end_time",
      hireDate: "hire_date",
      terminationDate: "termination_date"
    };
    Object.keys(mapping).forEach((key) => {
      if (key in obj && key !== mapping[key]) {
        obj[mapping[key]] = obj[key];
        delete obj[key];
      }
    });
  }`;

const fromDbFields = `private mapFromDbFields(obj: any) {
    const mapping: Record<string, string> = {
      is_radiographer: "isRadiographer",
      is_part_time: "isPartTime",
      is_health_mgmt: "isHealthMgmt",
      health_mgmt_location: "healthMgmtLocation",
      is_active: "isActive",
      resignation_date: "resignationDate",
      group_index: "groupIndex",
      group_id: "groupId",
      must_change_password: "mustChangePassword",
      avatar_url: "avatarUrl",
      personal_cycles: "personalCycles",
      primary_station: "primaryStation",
      learning_capabilities: "learningCapabilities",
      excluded_capabilities: "excludedCapabilities",
      special_roles: "specialRoles",
      target_user_id: "targetUserId",
      return_date: "returnDate",
      approver_id: "approverId",
      processed_at: "processedAt",
      role_to_swap: "roleToSwap",
      target_approval: "targetApproval",
      permissions: "permissions",
      user_id: "userId",
      work_time: "workTime",
      display_order: "displayOrder",
      monthly_target_shifts: "monthlyTargetShifts",
      excluded_days: "excludedDays",
      excluded_auto_schedule_locations: "excludedAutoScheduleLocations",
      fixed_shifts: "fixedShifts",
      weekday_settings: "weekdaySettings",
      explanation_task_type: "explanationTaskType",
      is_auto_generated: "isAutoGenerated",
      doctor_id: "doctorId",
      start_date: "startDate",
      end_date: "endDate",
      start_time: "startTime",
      end_time: "endTime",
      hire_date: "hireDate",
      termination_date: "terminationDate"
    };
    Object.keys(mapping).forEach((key) => {
      if (key in obj && key !== mapping[key]) {
        obj[mapping[key]] = obj[key];
        delete obj[key];
      }
    });
  }`;

if (code.match(regexTo)) {
  code = code.replace(regexTo, toDbFields);
  console.log('Replaced mapToDbFields');
} else {
  console.log('Could not find mapToDbFields');
}

if (code.match(regexFrom)) {
  code = code.replace(regexFrom, fromDbFields);
  console.log('Replaced mapFromDbFields');
} else {
  console.log('Could not find mapFromDbFields');
}

fs.writeFileSync('services/store.ts', code);
