const fs = require('fs');
let code = fs.readFileSync('services/store.ts', 'utf8');

const regexFrom = /private mapFromDbFields\(obj: any\) \{[\s\S]*?\/\/\s*No,\s*better\s*to\s*be\s*clean\s*\n\s*\}\s*\n\s*\}\);\s*\n\s*\}/;

const fromDbFields = `private mapFromDbFields(obj: any) {
    const mapping: Record<string, string> = {
      is_radiographer: "isRadiographer",
      is_part_time: "isPartTime",
      is_health_mgmt: "isHealthMgmt",
      health_mgmt_location: "healthMgmtLocation",
      is_active: "isActive",
      resignation_date: "resignationDate",
      group_index: "groupIndex",
      group_id: "groupId",
      must_change_password: "mustChangePassword",
      avatar_url: "avatarUrl",
      personal_cycles: "personalCycles",
      primary_station: "primaryStation",
      learning_capabilities: "learningCapabilities",
      excluded_capabilities: "excludedCapabilities",
      special_roles: "specialRoles",
      target_user_id: "targetUserId",
      return_date: "returnDate",
      approver_id: "approverId",
      processed_at: "processedAt",
      role_to_swap: "roleToSwap",
      target_approval: "targetApproval",
      permissions: "permissions",
      user_id: "userId",
      work_time: "workTime",
      display_order: "displayOrder",
      monthly_target_shifts: "monthlyTargetShifts",
      excluded_days: "excludedDays",
      excluded_auto_schedule_locations: "excludedAutoScheduleLocations",
      fixed_shifts: "fixedShifts",
      weekday_settings: "weekdaySettings",
      explanation_task_type: "explanationTaskType",
      is_auto_generated: "isAutoGenerated",
      doctor_id: "doctorId",
      start_date: "startDate",
      end_date: "endDate",
      start_time: "startTime",
      end_time: "endTime",
      hire_date: "hireDate",
      termination_date: "terminationDate"
    };
    Object.keys(mapping).forEach((key) => {
      if (key in obj && key !== mapping[key]) {
        obj[mapping[key]] = obj[key];
        delete obj[key];
      }
    });
  }`;

if (code.match(regexFrom)) {
  code = code.replace(regexFrom, fromDbFields);
  console.log('Replaced mapFromDbFields');
} else {
  console.log('Could not find mapFromDbFields');
}

fs.writeFileSync('services/store.ts', code);
