
export enum UserRole {
  SUPERVISOR = 'SUPERVISOR', // 部門主管
  EMPLOYEE = 'EMPLOYEE',     // 放射師/一般員工
  SYSTEM_ADMIN = 'SYSTEM_ADMIN', // 系統管理員
  SCHEDULER = 'SCHEDULER', // 排班管理員 (HR/醫師排班)
  VIEWER = 'VIEWER', // 瀏覽者 (僅查看)
}

export enum StaffGroup {
  GROUP_A = 'A',
  GROUP_B = 'B',
  GROUP_C = 'C'
}

export interface User {
  id: string;
  name: string;
  username: string; // New: Replaces email for login
  role: UserRole;
  groupId: StaffGroup;
  color?: string; // Specific color for the user avatar
  alias?: string; // New: Single character nickname/code displayed in avatar
  avatarUrl?: string; // Kept for backward compatibility
  capabilities?: string[]; // List of station names user is CERTIFIED in
  learningCapabilities?: string[]; // New: List of station names user is LEARNING
  excludedCapabilities?: string[]; // New: List of station names user is CERTIFIED but EXCLUDED from auto-schedule
  password?: string; // User defined password
  mustChangePassword?: boolean; // New: Force password change on next login
  primaryStation?: string; // New: Identifies the user's "Home" station (e.g., '遠距')
  isRadiographer?: boolean; // New: Flag to indicate if user should appear in Radiographer Schedule
}

// Updated Station Defaults: MR moved before US
export enum StationDefault {
  MR1_5T = 'MR1.5T',
  MR3T = 'MR3T',
  US1 = 'US1',
  US2 = 'US2',
  US3 = 'US3',
  US4 = 'US4',
  CT = 'CT',
  BMD_DX = 'BMD/DX',
  FLOOR_CONTROL = '場控',
  TECH_SUPPORT = '技術支援',
  REMOTE = '遠距',
  ADMIN = '行政',
  DAZHI_BRANCH = '大直',
  OFF = '休假',
  UNASSIGNED = '未分配'
}

export const SYSTEM_OFF = '休假';

export const SPECIAL_ROLES = {
  OPENING: '開機',
  LATE: '晚班',
  ASSIST: '輔班', // User called it "輔控", mapping to Assist/Support
  SCHEDULER: '排班',
  DAZHI_SUPPORT: '大直支援' // New: Remote staff supporting Dazhi
};

export interface Shift {
  id: string;
  userId: string;
  date: string; // ISO Date string YYYY-MM-DD
  station: string;
  specialRoles: string[];
  isAutoGenerated?: boolean;
  isRoleAutoGenerated?: boolean;
}

export enum LeaveType {
  PRE_SCHEDULED = '預假',
  CANCEL_LEAVE = '銷假',
  LONG_LEAVE = '長假',
  SWAP_SHIFT = '換假', // 雙向換假 (User A Work D1/Off D2 <-> User B Off D1/Work D2)
  ASK_LEAVE = '要假',  // 單向要假 (User A Work D1 -> User B Off D1)
  DUTY_SWAP = '任務換班' // 特殊任務換班 (開機/晚班)
}

export enum LeaveStatus {
  PENDING = '待審核',
  APPROVED = '已核准',
  REJECTED = '已駁回'
}

export interface LeaveRequest {
  id: string;
  userId: string;
  targetUserId?: string; // For Swap Shift
  startDate: string;
  endDate: string;
  returnDate?: string; // For Two-Way Swap Shift
  type: LeaveType;
  status: LeaveStatus;
  reason: string;
  createdAt: string;
  approverId?: string; // Who approved/rejected it
  processedAt?: string; // When it was processed

  // New fields for Duty Swap specificity & 2-step approval
  roleToSwap?: string; // E.g., '開機' or '晚班'
  targetApproval?: 'PENDING' | 'AGREED' | 'REJECTED'; // Status of the target user's agreement
}

export interface RosterCycle {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  isConfirmed?: boolean; // New: Lock status for the cycle
}

export enum DateEventType {
  NATIONAL = 'NATIONAL', // 國定假日
  MEETING = 'MEETING',   // 科會
  CLOSED = 'CLOSED',     // 休診 (全員預設休假)
  NOTE = 'NOTE',          // 備忘
  RADIOGRAPHER_NOTE = 'RADIOGRAPHER_NOTE', // 放射師備忘 (僅顯示於放射師排班)
  DOCTOR_NOTE = 'DOCTOR_NOTE' // 醫師備忘 (僅顯示於醫師排班)
}

export interface Holiday {
  id?: string; // Unique identifier
  date: string; // YYYY-MM-DD
  name: string;
  type: DateEventType;
}

export interface CycleAnchor {
  effectiveDate: string; // The date from which this logic applies (>=)
  anchorDate: string;    // The reference "Day 1" for calculation
}

export interface DailyManpowerStats {
  beitou_clients: number;
  beitou_cta: number;
  dazhi_clients: number;
  beitou_total?: number; // Manually entered total radiographer count for Beitou
}

export interface WeekdaySetting {
    dayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6; // 0=Sun, 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat
    workTime?: string; // e.g., "08:00-16:00"
    memo?: string;     // e.g., "亞東看診"
}

export interface Doctor {
    id: string;
    name: string;
    alias?: string; // Short name for display (e.g., '錢')
    specialty?: string; // New: e.g. "家醫科"
    capabilities?: string[]; // New: List of stations/skills this doctor can perform
    locations?: string[]; // New: List of locations (Beitou, Dazhi, Taichung)
    excludedDays?: number[]; // New: 0 (Sun) - 6 (Sat)
    excludedAutoScheduleLocations?: string[]; // New: Locations to exclude from auto-schedule
    isPartTime?: boolean; // New: Part-time doctor tag
    monthlyTargetShifts?: number; // New: Target number of shifts per month
    displayOrder?: number; // New: Custom display order (lower number = higher priority)
    fixedShifts?: FixedShift[]; // New: Fixed weekly shifts
    weekdaySettings?: WeekdaySetting[]; // New: Weekday-specific work hours and memos
}

export interface FixedShift {
    dayOfWeek: number; // 0=Sun, 1=Mon...
    station: string;
    location: string;
    workTime?: string;
}

export interface DoctorShift {
    id: string;
    doctorId: string;
    date: string; // YYYY-MM-DD
    station: string;
    explanationTaskType?: 'with_task' | 'standalone'; // Type of explanation task: 'with_task' (+解说) or 'standalone' ((解说))
    workTime?: string; // New: Working hours (e.g. "08:00-12:00")
    location?: string; // New: Beitou, Dazhi, Taichung
    task?: string; // New: Additional task (e.g. Late shift), displayed with note
    note?: string; // New: Special notes
    isAutoGenerated?: boolean; // New: Flag for auto-scheduled items
    scheduled_station?: string; // New: Actual schedule (CT, MR, US) vs Allocation (station)
}

export interface DoctorStationConfig {
  name: string;
  location: string; // '北投' | '大直' | '台中'
}

export interface SystemSettings {
  stations: string[];
  cycles: RosterCycle[];
  holidays: Holiday[]; // Renamed internally as special dates/holidays
  // Map of Station Name -> Array of 7 numbers [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
  stationRequirements: Record<string, number[]>;
  cycleStartDate?: string; // Legacy: Global fallback
  cycleAnchors?: CycleAnchor[]; // New: Multiple reset points
  stationDisplayOrder?: string[]; // New: Order of stations/roles in dashboard
  userDisplayOrder?: string[]; // New: Order of user IDs in dashboard
  dailyStats?: Record<string, DailyManpowerStats>; // New: Date (YYYY-MM-DD) -> Stats
  doctorStations?: DoctorStationConfig[]; // New: Configurable doctor stations with location
  doctorSpecialties?: string[]; // New: Configurable doctor specialties
  lineCopyTemplate?: string; // Custom template for 'Copy to Line'
  defaultDoctorWorkTime?: string; // Default work time for auto-schedule
  doctorWorkTimeOptions?: string[]; // New: List of available work times
  lockedMonths?: string[]; // New: List of locked months (YYYY-MM)
}


