
export enum UserRole {
  SUPERVISOR = 'SUPERVISOR', // 部門主管
  EMPLOYEE = 'EMPLOYEE',     // 放射師/一般員工
  SYSTEM_ADMIN = 'SYSTEM_ADMIN', // 系統管理員
}

export enum StaffGroup {
  GROUP_A = 'A',
  GROUP_B = 'B',
  GROUP_C = 'C'
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  groupId: StaffGroup;
  color?: string; // Specific color for the user avatar
  alias?: string; // New: Single character nickname/code displayed in avatar
  avatarUrl?: string; // Kept for backward compatibility
  capabilities?: string[]; // List of station names user is CERTIFIED in
  learningCapabilities?: string[]; // New: List of station names user is LEARNING
  excludedCapabilities?: string[]; // New: List of station names user is CERTIFIED but EXCLUDED from auto-schedule
  password?: string; // User defined password
  mustChangePassword?: boolean; // New: Force password change on next login
}

// Updated Station Defaults: MR moved before US
export enum StationDefault {
  MR1_5T = 'MR1.5T',
  MR3T = 'MR3T',
  US1 = 'US1',
  US2 = 'US2',
  US3 = 'US3',
  US4 = 'US4',
  CT = 'CT',
  BMD_DX = 'BMD/DX',
  FLOOR_CONTROL = '場控',
  TECH_SUPPORT = '技術支援',
  REMOTE = '遠距',
  ADMIN = '行政',
  DAZHI_BRANCH = '大直',
  OFF = '休假',
  UNASSIGNED = '未分配'
}

export const SYSTEM_OFF = '休假';

export const SPECIAL_ROLES = {
  OPENING: '開機',
  LATE: '晚班',
  ASSIST: '輔班', // User called it "輔控", mapping to Assist/Support
  SCHEDULER: '排班'
};

export interface Shift {
  id: string;
  userId: string;
  date: string; // ISO Date string YYYY-MM-DD
  station: string;
  specialRoles: string[];
  isAutoGenerated?: boolean;
  isRoleAutoGenerated?: boolean;
}

export enum LeaveType {
  PRE_SCHEDULED = '預假',
  CANCEL_LEAVE = '銷假',
  LONG_LEAVE = '長假',
  SWAP_SHIFT = '換假', // 一般換休
  DUTY_SWAP = '任務換班' // 特殊任務換班 (開機/晚班)
}

export enum LeaveStatus {
  PENDING = '待審核',
  APPROVED = '已核准',
  REJECTED = '已駁回'
}

export interface LeaveRequest {
  id: string;
  userId: string;
  targetUserId?: string; // For Swap Shift
  startDate: string;
  endDate: string;
  type: LeaveType;
  status: LeaveStatus;
  reason: string;
  createdAt: string;
  approverId?: string; // Who approved/rejected it
  processedAt?: string; // When it was processed

  // New fields for Duty Swap specificity & 2-step approval
  roleToSwap?: string; // E.g., '開機' or '晚班'
  targetApproval?: 'PENDING' | 'AGREED' | 'REJECTED'; // Status of the target user's agreement
}

export interface RosterCycle {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  isConfirmed?: boolean; // New: Lock status for the cycle
}

export enum DateEventType {
  NATIONAL = 'NATIONAL', // 國定假日
  MEETING = 'MEETING',   // 科會
  CLOSED = 'CLOSED'      // 休診 (全員預設休假)
}

export interface Holiday {
  date: string; // YYYY-MM-DD
  name: string;
  type: DateEventType;
}

export interface SystemSettings {
  stations: string[];
  cycles: RosterCycle[];
  holidays: Holiday[]; // Renamed internally as special dates/holidays
  // Map of Station Name -> Array of 7 numbers [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
  stationRequirements: Record<string, number[]>;
  cycleStartDate?: string; // New: The reference date for 4-on-2-off calculation
  stationDisplayOrder?: string[]; // New: Order of stations/roles in dashboard
  userDisplayOrder?: string[]; // New: Order of user IDs in dashboard
}
