import { describe, expect, it } from "vitest";
import { LeaveType } from "../types";
import { buildSwapLeaveShiftUpdates } from "./leaveShiftUpdates";

describe("approved two-way leave swap shift updates", () => {
  it("creates both OFF rows and both WORK rows", () => {
    const shifts = buildSwapLeaveShiftUpdates({
      id: "leave-1",
      type: LeaveType.SWAP_SHIFT,
      userId: "requestor",
      targetUserId: "target",
      startDate: "2026-12-12",
      returnDate: "2026-12-16",
    });

    expect(
      shifts.map(({ userId, date, station, isAutoGenerated }) => ({
        userId,
        date,
        station,
        isAutoGenerated,
      })),
    ).toEqual([
      {
        userId: "requestor",
        date: "2026-12-12",
        station: "休假",
        isAutoGenerated: false,
      },
      {
        userId: "target",
        date: "2026-12-12",
        station: "未分配",
        isAutoGenerated: false,
      },
      {
        userId: "requestor",
        date: "2026-12-16",
        station: "未分配",
        isAutoGenerated: false,
      },
      {
        userId: "target",
        date: "2026-12-16",
        station: "休假",
        isAutoGenerated: false,
      },
    ]);
  });

  it("does not create partial updates when the swap is incomplete", () => {
    expect(
      buildSwapLeaveShiftUpdates({
        id: "leave-2",
        type: LeaveType.SWAP_SHIFT,
        userId: "requestor",
        startDate: "2026-12-12",
        returnDate: "2026-12-16",
      }),
    ).toEqual([]);
  });
});
