import {
  LeaveRequest,
  LeaveType,
  Shift,
  StationDefault,
  SYSTEM_OFF,
} from "../types";

type SwapLeave = Pick<
  LeaveRequest,
  "id" | "type" | "userId" | "targetUserId" | "startDate" | "returnDate"
>;

/**
 * Produces all four sides of a two-way leave swap. Keeping this pure and
 * centralized prevents an approved request from writing only the OFF rows
 * while omitting the corresponding WORK rows.
 */
export const buildSwapLeaveShiftUpdates = (leave: SwapLeave): Shift[] => {
  if (
    leave.type !== LeaveType.SWAP_SHIFT ||
    !leave.targetUserId ||
    !leave.returnDate
  ) {
    return [];
  }

  const makeShift = (
    userId: string,
    date: string,
    station: string,
  ): Shift => ({
    id: `${userId}-${date}`,
    userId,
    date,
    station,
    specialRoles: [],
    isAutoGenerated: false,
    isRoleAutoGenerated: false,
  });

  return [
    makeShift(leave.userId, leave.startDate, SYSTEM_OFF),
    makeShift(leave.targetUserId, leave.startDate, StationDefault.UNASSIGNED),
    makeShift(leave.userId, leave.returnDate, StationDefault.UNASSIGNED),
    makeShift(leave.targetUserId, leave.returnDate, SYSTEM_OFF),
  ];
};
