import { describe, expect, it } from "vitest";
import type { Doctor, DoctorShift } from "../types";
import { addLateShiftTask, getLateShiftCandidates, hasLateShiftTask, removeLateShiftTask } from "./physicianLateShift";

const date = "2026-09-27";
const doctors: Doctor[] = [
  { id: "beitou", name: "北投醫師", capabilities: [] },
  { id: "dazhi", name: "大直醫師" },
  { id: "off", name: "休假醫師", capabilities: ["晚班"] },
  { id: "absent", name: "未排班醫師", capabilities: ["晚班"] },
];
const shift = (doctorId: string, location: string, station = "影像"): DoctorShift => ({
  id: doctorId,
  doctorId,
  date,
  station,
  location,
});

describe("晚班依當天實際上班院區指定", () => {
  const shifts = [shift("beitou", "北投"), shift("dazhi", "大直"), shift("off", "北投", "OFF")];

  it.each([ ["北投", "beitou"], ["大直", "dazhi"] ])("%s 只列出該院區當天上班醫師，包含未設定晚班技能者", (location, id) => {
    expect(getLateShiftCandidates(doctors, shifts, date, location).map(({ doctor }) => doctor.id)).toEqual([id]);
  });

  it.each(["北投", "大直"])("%s 排除兼職及麻醉醫師", (location) => {
    const excluded: Doctor[] = [
      { id: "part-time", name: "兼職醫師", isPartTime: true },
      { id: "anes-specialty", name: "麻醉科醫師", specialty: "麻醉科" },
      { id: "anes-skill", name: "麻醉醫師", capabilities: ["麻醉"] },
      { id: "anes-shift", name: "當日麻醫" },
    ];
    const workingShifts = excluded.map((doctor) =>
      shift(doctor.id, location, doctor.id === "anes-shift" ? "麻醉" : "影像"),
    );
    expect(getLateShiftCandidates(excluded, workingShifts, date, location)).toEqual([]);
  });

  it("不列出其他日期、未排班、已停用或院區不明者", () => {
    expect(getLateShiftCandidates(doctors, shifts, "2026-09-28", "北投")).toEqual([]);
    expect(getLateShiftCandidates([{ ...doctors[0], isActive: false }], shifts, date, "北投")).toEqual([]);
    expect(getLateShiftCandidates(doctors, [{ ...shifts[0], location: undefined }], date, "北投")).toEqual([]);
  });

  it.each(["X", "OFF", "休假", "Unassigned", "未分配"])("實際排班為 %s 時不可指定", (scheduled_station) => {
    expect(getLateShiftCandidates(doctors, [{ ...shifts[0], scheduled_station }], date, "北投")).toEqual([]);
  });

  it("以當日實際排班為準，固定不報到日仍已排班者可以指定", () => {
    expect(getLateShiftCandidates([{ ...doctors[0], excludedDays: [0] }], shifts, date, "北投")).toHaveLength(1);
  });

  it("新增晚班保留完整原班表與任務，重複指定不會重複加入", () => {
    const original: DoctorShift = { ...shifts[0], scheduled_station: "CT", workTime: "08:00-16:00", note: "原備註", task: "電台, 解說", isAutoGenerated: false };
    const updated = addLateShiftTask(original);
    expect(updated).toEqual({ ...original, task: "電台, 解說, 晚班" });
    expect(original.task).toBe("電台, 解說");
    expect(addLateShiftTask(updated)).toEqual(updated);
    expect(addLateShiftTask(shifts[1]).task).toBe("晚班");
  });
});


describe("清除晚班", () => {
  it.each(["電台, 晚班, 解說", "晚班，電台，解說", "電台、解說、晚班"])("只清除晚班，保留其他任務與班表欄位：%s", (task) => {
    const original: DoctorShift = {
      ...shift("beitou", "北投"), scheduled_station: "CT",
      workTime: "08:00-16:00", note: "原備註", task,
      isAutoGenerated: false,
    };
    expect(removeLateShiftTask(original)).toEqual({ ...original, task: "電台, 解說" });
    expect(original.task).toBe(task);
  });

  it("只有晚班時清為空字串，原崗位不變", () => {
    const original = { ...shift("dazhi", "大直"), task: "晚班" };
    expect(removeLateShiftTask(original)).toEqual({ ...original, task: "" });
    expect(hasLateShiftTask(removeLateShiftTask(original))).toBe(false);
  });

  it("沒有晚班時不更動其他任務，包括含晚班字樣的備註任務", () => {
    for (const task of [undefined, "", "電台,  解說", "晚班交接說明"]) {
      const original = { ...shift("beitou", "北投"), task };
      expect(removeLateShiftTask(original)).toEqual(original);
    }
  });

  it("之前已排晚班的兼職或麻醉醫師仍可清除任務", () => {
    const excluded: Doctor[] = [
      { id: "part-time", name: "兼職醫師", isPartTime: true },
      { id: "anes", name: "麻醫", specialty: "麻醉科" },
    ];
    const existing = excluded.map((doctor) => ({ ...shift(doctor.id, "北投"), task: "晚班, 電台" }));
    expect(getLateShiftCandidates(excluded, existing, date, "北投")).toEqual([]);
    expect(existing.filter(hasLateShiftTask)).toHaveLength(2);
    expect(existing.map(removeLateShiftTask).map((s) => s.task)).toEqual(["電台", "電台"]);
  });
});
