import { describe, expect, it } from "vitest";
import type { Doctor, DoctorShift } from "../types";
import { addLateShiftTask, getLateShiftCandidates } from "./physicianLateShift";

const date = "2026-09-27";
const doctors: Doctor[] = [
  { id: "beitou", name: "北投醫師", capabilities: [] },
  { id: "dazhi", name: "大直醫師", isPartTime: true },
  { id: "off", name: "休假醫師", capabilities: ["晚班"] },
  { id: "absent", name: "未排班醫師", capabilities: ["晚班"] },
];
const shift = (doctorId: string, location: string, station = "影像"): DoctorShift => ({
  id: doctorId,
  doctorId,
  date,
  station,
  location,
});

describe("晚班依當天實際上班院區指定", () => {
  const shifts = [shift("beitou", "北投"), shift("dazhi", "大直"), shift("off", "北投", "OFF")];

  it.each([ ["北投", "beitou"], ["大直", "dazhi"] ])("%s 只列出該院區當天上班醫師，包含兼職及未設定晚班技能者", (location, id) => {
    expect(getLateShiftCandidates(doctors, shifts, date, location).map(({ doctor }) => doctor.id)).toEqual([id]);
  });

  it("不列出其他日期、未排班、已停用或院區不明者", () => {
    expect(getLateShiftCandidates(doctors, shifts, "2026-09-28", "北投")).toEqual([]);
    expect(getLateShiftCandidates([{ ...doctors[0], isActive: false }], shifts, date, "北投")).toEqual([]);
    expect(getLateShiftCandidates(doctors, [{ ...shifts[0], location: undefined }], date, "北投")).toEqual([]);
  });

  it.each(["X", "OFF", "休假", "Unassigned", "未分配"])("實際排班為 %s 時不可指定", (scheduled_station) => {
    expect(getLateShiftCandidates(doctors, [{ ...shifts[0], scheduled_station }], date, "北投")).toEqual([]);
  });

  it("以當日實際排班為準，固定不報到日仍已排班者可以指定", () => {
    expect(getLateShiftCandidates([{ ...doctors[0], excludedDays: [0] }], shifts, date, "北投")).toHaveLength(1);
  });

  it("新增晚班保留完整原班表與任務，重複指定不會重複加入", () => {
    const original: DoctorShift = { ...shifts[0], scheduled_station: "CT", workTime: "08:00-16:00", note: "原備註", task: "電台, 解說", isAutoGenerated: false };
    const updated = addLateShiftTask(original);
    expect(updated).toEqual({ ...original, task: "電台, 解說, 晚班" });
    expect(original.task).toBe("電台, 解說");
    expect(addLateShiftTask(updated)).toEqual(updated);
    expect(addLateShiftTask(shifts[1]).task).toBe("晚班");
  });
});
